# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI_Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Build_Example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Setup enviorment
      run: sudo apt-get install libgl1-mesa-dev xorg-dev

    - name: Build Example
      run: go build -o bin/example example/example.go

  Build_Test1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Setup enviorment
      run: sudo apt-get install libgl1-mesa-dev xorg-dev

    - name: Build Test1
      run: go build -o bin/test1 tests/test1/test.go
